In [1]:
import pandas as pd

In [14]:
df = pd.read_json("../resources/nuforc/2023-03-20T07-03-34.json", lines=True)
df

,date_time,city,state,country,shape,duration,summary,posted,images,url,year_month
0,2013-09-30 22:30:00,Glen Gardner,NJ,USA,Unknown,20 minutes,Stat. obj. high in the sky that had rapidly fl...,10/3/13,None,https://nuforc.org/webreports/ndxe201309.html,2013-09
1,2013-10-31 22:15:00,Erode (India),None,India,Rectangle,1 minute,"Greenish box shape object at Erode, India.",11/11/13,None,https://nuforc.org/webreports/ndxe201310.html,2013-10
2,2003-08-31 23:30:00,Mulino,OR,USA,Triangle,1 minute,Triangle of white lights heading north at high...,9/28/03,None,https://nuforc.org/webreports/ndxe200308.html,2003-08
3,2003-09-30 22:34:00,Poplar Grove,IL,USA,Light,10 Minutes,TWO brightly lit UFO's spotted near Poplar Gro...,10/7/03,None,https://nuforc.org/webreports/ndxe200309.html,2003-09
4,2003-10-31 23:00:00,Tucson,AZ,USA,Triangle,8 Hours,"Visible by the naked eye, appear to be several...",11/8/03,None,https://nuforc.org/webreports/ndxe200310.html,2003-10
...,...,...,...,...,...,...,...,...,...,...,...
139760,2022-06-01 03:36:00,Dayton,MN,USA,Light,a few seconds,"Pulsing bright blue light flashing across sky,...",6/22/22,None,https://nuforc.org/webreports/ndxe202206.html,2022-06
139761,2022-06-01 03:00:00,Shohola,PA,USA,Cylinder,6-8 seconds,Thick white bar of light descends while moving...,6/22/22,Yes,https://nuforc.org/webreports/ndxe202206.html,2022-06
139762,2022-06-01 01:19:00,Dubai,Dubai,United Arab Emirates,Unknown,I am a living human alien,I am a living human alien hybrid,6/22/22,None,https://nuforc.org/webreports/ndxe202206.html,2022-06
139763,2022-06-01 00:01:00,Kyiv,None,Ukraine,Other,1 hour,Z - shaped formation of UFOs,6/22/22,Yes,https://nuforc.org/webreports/ndxe202206.html,2022-06
139764,2022-06-01 00:00:00,Kyiv,None,Ukraine,Other,1 hour,Z shape UFO formation,6/22/22,None,https://nuforc.org/webreports/ndxe202206.html,2022-06

In [16]:
date_cols = ["date_time", "posted"]
df[date_cols] = df[date_cols].apply(pd.to_datetime)
df.sort_values("date_time", inplace=True)
df[date_cols]

                date_time     posted
20891 1973-01-01 23:30:00 1999-12-16
20890 1973-01-02 23:00:00 2009-05-12
20889 1973-01-08 21:00:00 2006-03-11
20888 1973-01-10 02:30:00 1998-11-19
20887 1973-01-12 03:00:00 2002-11-20
...                   ...        ...
20882 2072-12-01 20:00:00 2003-07-16
20881 2072-12-06 00:00:00 2005-09-15
20880 2072-12-12 15:00:00 2007-02-24
20879 2072-12-16 22:30:00 2005-09-02
20878 2072-12-24 02:00:00 2011-12-12

[139765 rows x 2 columns]

In [17]:
df.loc[df.images == "Yes"]

,date_time,city,state,country,shape,duration,summary,posted,images,url,year_month
21500,1975-09-01 21:30:00,Dallas,TX,USA,Disk,5 minutes,"A large disk craft hovered over 635, then inst...",2022-09-09,Yes,https://nuforc.org/webreports/ndxe197509.html,1975-09
22131,1978-05-19 21:25:00,Tiller,OR,USA,Disk,1977-1979,Alien in human form and many size and shape of...,2022-12-22,Yes,https://nuforc.org/webreports/ndxe197805.html,1978-05
22274,1978-12-18 18:00:00,Albuquerque,NM,USA,Circle,Approx. 30 sec to 1 min,"Flat, Round, Fully Illuminated UFO over Neighb...",2022-03-04,Yes,https://nuforc.org/webreports/ndxe197812.html,1978-12
22551,1980-01-03 16:50:00,Los Angeles,CA,USA,Disk,Approximately 10 minutes,A huge brightly-lit aerial object approached a...,2023-03-06,Yes,https://nuforc.org/webreports/ndxe198001.html,1980-01
23560,1984-11-08 20:00:00,Brewster,NY,USA,Unknown,10 minutes,Massive black “ship” moving slowly about 3X tr...,2022-12-22,Yes,https://nuforc.org/webreports/ndxe198411.html,1984-11
...,...,...,...,...,...,...,...,...,...,...,...
18595,2057-09-05 19:15:00,Nashville,KS,USA,Cigar,2 1/2 hours,My mother said a UFO chased us down a highway.,2023-03-06,Yes,https://nuforc.org/webreports/ndxe195709.html,1957-09
19152,2064-06-21 20:00:00,"South Ozone Park, Queens, NYC",NY,USA,Disk,5 minutes total,"Playing in the dark, suddenly lit up like day ...",2022-03-04,Yes,https://nuforc.org/webreports/ndxe196406.html,1964-06
19826,2068-02-28 18:15:00,McKenzie Bridge,OR,USA,Disk,6 seconds,Very unusual disc shaped object observed throu...,2022-05-31,Yes,https://nuforc.org/webreports/ndxe196802.html,1968-02
20318,2069-07-01 11:00:00,Redding,CA,USA,None,30 to 40 seconds,"The craft was black, it was similar to a Chino...",2022-09-09,Yes,https://nuforc.org/webreports/ndxe196907.html,1969-07
20423,2070-03-07 09:00:00,Bonney lake,WA,USA,Circle,30 seconds,2 ufos 20ft and 5ft,2022-10-08,Yes,https://nuforc.org/webreports/ndxe197003.html,1970-03