In [2]:
import pandas as pd

In [3]:
df = pd.read_json("../downloads/nuforc/2023-07-28T01-19-46.json", lines=True)
df

,date_time,city,state,country,shape,duration,summary,posted,images,url,year_month
0,2014-06-30 23:30:00,Sylmar,CA,USA,Fireball,15 minutes,"Cluster of flying orbs seen over Sylmar, CA",7/4/14,None,https://nuforc.org/webreports/ndxe201406.html,2014-06
1,2014-05-31 23:40:00,Springfield,MO,USA,Sphere,5 minutes,"Saw 10 orange spheres, all were going in diffe...",6/4/14,None,https://nuforc.org/webreports/ndxe201405.html,2014-05
2,2014-06-30 22:34:00,Corona,CA,USA,Changing,>30 minutes,2 objects in the sky facing the south sky. The...,7/4/14,None,https://nuforc.org/webreports/ndxe201406.html,2014-06
3,2014-06-30 22:12:00,Kittery,ME,USA,Triangle,2 minutes,60 foot long UFO silently passes over security...,1/9/15,None,https://nuforc.org/webreports/ndxe201406.html,2014-06
4,2014-06-30 22:03:00,Elk Grove,CA,USA,Circle,30 seconds,"Fast moving star like ufo stops its course, li...",7/4/14,None,https://nuforc.org/webreports/ndxe201406.html,2014-06
...,...,...,...,...,...,...,...,...,...,...,...
139760,2020-04-01 10:00:00,Johnscreek,GA,USA,Circle,10,"Glowing circular disc was spinning clock wise,...",5/15/20,None,https://nuforc.org/webreports/ndxe202004.html,2020-04
139761,2020-04-01 09:45:00,Woodbury,MN,USA,Sphere,1 minutes,I was looking out my window and saw a bright w...,6/25/20,None,https://nuforc.org/webreports/ndxe202004.html,2020-04
139762,2020-04-01 09:28:00,Nairobi (Kenya),None,Kenya,Sphere,15-20 minutes,Shining sphere,6/25/20,None,https://nuforc.org/webreports/ndxe202004.html,2020-04
139763,2020-04-01 04:00:00,Anderson,SC,USA,Light,30+ minutes,2 lights appeared out of nowhere just down and...,6/25/20,None,https://nuforc.org/webreports/ndxe202004.html,2020-04
139764,2020-04-01 03:45:00,Petersham,MA,USA,Fireball,2+ minutes,"Ok, this is NOT an April fools joke. At 3:45 t...",4/9/20,None,https://nuforc.org/webreports/ndxe202004.html,2020-04

In [4]:
date_cols = ["date_time", "posted"]
df[date_cols] = df[date_cols].apply(pd.to_datetime)
df.sort_values("date_time", inplace=True)
df[date_cols]

                date_time     posted
21303 1973-01-01 23:30:00 1999-12-16
21302 1973-01-02 23:00:00 2009-05-12
21301 1973-01-08 21:00:00 2006-03-11
21300 1973-01-10 02:30:00 1998-11-19
21299 1973-01-12 03:00:00 2002-11-20
...                   ...        ...
21308 2072-12-01 20:00:00 2003-07-16
21307 2072-12-06 00:00:00 2005-09-15
21306 2072-12-12 15:00:00 2007-02-24
21305 2072-12-16 22:30:00 2005-09-02
21304 2072-12-24 02:00:00 2011-12-12

[139765 rows x 2 columns]

In [5]:
df.loc[df.images == "Yes"]

,date_time,city,state,country,shape,duration,summary,posted,images,url,year_month
22023,1975-09-01 21:30:00,Dallas,TX,USA,Disk,5 minutes,"A large disk craft hovered over 635, then inst...",2022-09-09,Yes,https://nuforc.org/webreports/ndxe197509.html,1975-09
22572,1978-05-19 21:25:00,Tiller,OR,USA,Disk,1977-1979,Alien in human form and many size and shape of...,2022-12-22,Yes,https://nuforc.org/webreports/ndxe197805.html,1978-05
22732,1978-12-18 18:00:00,Albuquerque,NM,USA,Circle,Approx. 30 sec to 1 min,"Flat, Round, Fully Illuminated UFO over Neighb...",2022-03-04,Yes,https://nuforc.org/webreports/ndxe197812.html,1978-12
22980,1980-01-03 16:50:00,Los Angeles,CA,USA,Disk,Approximately 10 minutes,A huge brightly-lit aerial object approached a...,2023-03-06,Yes,https://nuforc.org/webreports/ndxe198001.html,1980-01
24036,1984-11-08 20:00:00,Brewster,NY,USA,Unknown,10 minutes,Massive black “ship” moving slowly about 3X tr...,2022-12-22,Yes,https://nuforc.org/webreports/ndxe198411.html,1984-11
...,...,...,...,...,...,...,...,...,...,...,...
19016,2057-09-05 19:15:00,Nashville,KS,USA,Cigar,2 1/2 hours,My mother said a UFO chased us down a highway.,2023-03-06,Yes,https://nuforc.org/webreports/ndxe195709.html,1957-09
19546,2064-06-21 20:00:00,"South Ozone Park, Queens, NYC",NY,USA,Disk,5 minutes total,"Playing in the dark, suddenly lit up like day ...",2022-03-04,Yes,https://nuforc.org/webreports/ndxe196406.html,1964-06
20426,2068-02-28 18:15:00,McKenzie Bridge,OR,USA,Disk,6 seconds,Very unusual disc shaped object observed throu...,2022-05-31,Yes,https://nuforc.org/webreports/ndxe196802.html,1968-02
20723,2069-07-01 11:00:00,Redding,CA,USA,None,30 to 40 seconds,"The craft was black, it was similar to a Chino...",2022-09-09,Yes,https://nuforc.org/webreports/ndxe196907.html,1969-07
20841,2070-03-07 09:00:00,Bonney lake,WA,USA,Circle,30 seconds,2 ufos 20ft and 5ft,2022-10-08,Yes,https://nuforc.org/webreports/ndxe197003.html,1970-03